---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    purpose: test
    todelete: fuck
    another: label
    just: another
    dont: usebools
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
